version: '3'
services:

  # VISUALIZADOR DO CLUSTER
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager

  # AIRFLOW DATABASE
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=airflow

  # AIRFLOW
  airflow:
    image: akkidx/airflow:blog1
    #build:
      #context: "../Dockerfile"
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://admin:admin@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_CONN_MYSQL='mysql://admin:admin@mysqldb:3306/fiap'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./dags:/opt/airflow/dags

    ports:
      - "18080:18080"

  # CURSO DATABASE : exemplo MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - 8082:80  
    restart: unless-stopped
    depends_on: 
      - mysqldb
    
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: usuarios
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - "./mysql_init_database.sql:/docker-entrypoint-initdb.d/init-database.sql"
      - "./mysql.cnf:/etc/mysql/conf.d/mysql.cnf"

volumes:
  mysqldata:
