version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=airflow

  airflow:
    image: akkidx/airflow:blog1
    #build:
      #context: "../Dockerfile"
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://admin:admin@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./swarm_operator.py:/root/airflow/dags/swarm_operator.py"
    ports:
      - "18080:18080"
