FROM apache/airflow:slim-3.1.8-python3.13

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         nano \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir pymysql
