FROM tonanuvem/airflow:hive

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         nano \
         vi \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir pymysql
