FROM apache/airflow
#FROM akkidx/airflow:blog1

RUN pip install --no-cache-dir apache-airflow-providers-docker
RUN pip install --no-cache-dir apache-airflow-providers-apache-hive

COPY --chown=airflow:root ./dags/mysql_to_hive.py /opt/airflow/dags
COPY --chown=airflow:root ./dags/swarm_operator.py /opt/airflow/dags
