FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD admin
ENV MYSQL_DATABASE fiap
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD admin

COPY ../config/mysql_init_database.sql /docker-entrypoint-initdb.d/init-database.sql
COPY ../config/mysql.cnf /etc/mysql/conf.d/mysql.cnf"
